project_name: micro
release:
  github:
    owner: alex-dna-tech
    name: micro
  name_template: 'Release {{ .Tag }}'

env:
  - CGO_ENABLED=1
builds:
  - id: micro-darwin-amd64
    binary: micro
    main: ./cmd/micro
    goarch:
      - amd64
    goos:
      - darwin
    env:
      - CC=o64-clang
      - CXX=o64-clang++
    flags:
      - -trimpath

  - id: micro-darwin-arm64
    binary: micro
    main: ./cmd/micro
    goarch:
      - arm64
    goos:
      - darwin
    env:
      - CC=oa64-clang
      - CXX=oa64-clang++
    flags:
      - -trimpath

  - id: micro-linux-amd64
    binary: micro
    main: ./cmd/micro
    goarch:
      - amd64
    goos:
      - linux
    env:
      - CC=x86_64-linux-gnu-gcc
      - CXX=x86_64-linux-gnu-g++
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X micro.dev/v4/cmd.GitCommit={{ .ShortCommit }}
      - -X micro.dev/v4/cmd.GitTag={{ .Tag }}
      - -X micro.dev/v4/cmd.BuildDate={{ .Timestamp }}

  - id: micro-linux-arm64
    binary: micro
    main: ./cmd/micro
    goarch:
      - arm64
    goos:
      - linux
    env:
      - CC=aarch64-linux-gnu-gcc
      - CXX=aarch64-linux-gnu-g++
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X micro.dev/v4/cmd.GitCommit={{ .ShortCommit }}
      - -X micro.dev/v4/cmd.GitTag={{ .Tag }}
      - -X micro.dev/v4/cmd.BuildDate={{ .Timestamp }}

  - id: micro-linux-armhf
    binary: micro
    main: ./cmd/micro
    goarch:
      - arm
    goarm:
      - 7
    goos:
      - linux
    env:
      - CC=arm-linux-gnueabihf-gcc
      - CXX=arm-linux-gnueabihf-g++
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X micro.dev/v4/cmd.GitCommit={{ .ShortCommit }}
      - -X micro.dev/v4/cmd.GitTag={{ .Tag }}
      - -X micro.dev/v4/cmd.BuildDate={{ .Timestamp }}

  - id: micro-windows-amd64
    binary: micro
    main: ./cmd/micro
    goarch:
      - amd64
    goos:
      - windows
    env:
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
    flags:
      - -trimpath
      - -buildmode=exe

  - id: micro-windows-386
    binary: micro
    main: ./cmd/micro
    goarch:
      - 386
    goos:
      - windows
    env:
      - CC=/llvm-mingw/bin/i686-w64-mingw32-gcc
      - CXX=/llvm-mingw/bin/i686-w64-mingw32-g++
    flags:
      - -trimpath
      - -buildmode=exe


  - id: micro-windows-arm64
    binary: micro
    main: ./cmd/micro
    goarch:
      - arm64
    goos:
      - windows
    env:
      - CC=/llvm-mingw/bin/aarch64-w64-mingw32-gcc
      - CXX=/llvm-mingw/bin/aarch64-w64-mingw32-g++
    flags:
      - -trimpath
      - -buildmode=exe

archives:
  - id: release/version
    builds:
      - micro-darwin-amd64
      - micro-darwin-arm64
      - micro-linux-amd64
      - micro-linux-arm64
      - micro-linux-armhf
      - micro-windows-amd64
      - micro-windows-386
      - micro-windows-arm64
    name_template: '{{ .ProjectName }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}{{ .Arm }}'
    wrap_in_directory: false
    format: tar.gz
    format_overrides:
    - goos: windows
      format: zip
    files:
      - LICENSE
      - README.md
checksum:
  name_template: 'checksums.txt'
  algorithm: sha256
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

dockers:
- image_templates:
    - "docker.io/dnat4/{{ .ProjectName }}:latest"
    - "docker.io/dnat4/{{ .ProjectName }}:{{ .RawVersion }}"
    - "docker.io/dnat4/{{ .ProjectName }}:{{ .Major }}"
    - "docker.io/dnat4/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}"
    - "docker.io/dnat4/{{ .ProjectName }}:{{ .Tag }}"

    - "ghcr.io/alex-dna-tech/{{ .ProjectName }}:latest"
    - "ghcr.io/alex-dna-tech/{{ .ProjectName }}:{{ .RawVersion }}"
    - "ghcr.io/alex-dna-tech/{{ .ProjectName }}:{{ .Major }}"
    - "ghcr.io/alex-dna-tech/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}"
    - "ghcr.io/alex-dna-tech/{{ .ProjectName }}:{{ .Tag }}"
  dockerfile: Dockerfile
  build_flag_templates:
    - --platform=linux/amd64
    - --label=org.opencontainers.image.title={{ .ProjectName }}
    - --label=org.opencontainers.image.description={{ .ReleaseNotes }}
    - --label=org.opencontainers.image.url={{ .ReleaseURL }}
    - --label=org.opencontainers.image.source={{ .GitURL }}
    - --label=org.opencontainers.image.version={{ .RawVersion }}
    - --label=org.opencontainers.image.created={{ .Timestamp }}
    - --label=org.opencontainers.image.revision={{ .FullCommit }}
    - --label=org.opencontainers.image.licenses=MIT

- image_templates:
    - "docker.io/dnat4/{{ .ProjectName }}:latest"
    - "docker.io/dnat4/{{ .ProjectName }}:{{ .RawVersion }}"
    - "docker.io/dnat4/{{ .ProjectName }}:{{ .Major }}"
    - "docker.io/dnat4/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}"
    - "docker.io/dnat4/{{ .ProjectName }}:{{ .Tag }}"

    - "ghcr.io/alex-dna-tech/{{ .ProjectName }}:latest"
    - "ghcr.io/alex-dna-tech/{{ .ProjectName }}:{{ .RawVersion }}"
    - "ghcr.io/alex-dna-tech/{{ .ProjectName }}:{{ .Major }}"
    - "ghcr.io/alex-dna-tech/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}"
    - "ghcr.io/alex-dna-tech/{{ .ProjectName }}:{{ .Tag }}"
  goarch: arm64
  dockerfile: Dockerfile
  build_flag_templates:
  - --platform=linux/arm64/v8
  - --label=org.opencontainers.image.title={{ .ProjectName }}
  - --label=org.opencontainers.image.description={{ .ReleaseNotes }}
  - --label=org.opencontainers.image.url={{ .ReleaseURL }}
  - --label=org.opencontainers.image.source={{ .GitURL }}
  - --label=org.opencontainers.image.version={{ .RawVersion }}
  - --label=org.opencontainers.image.created={{ .Timestamp }}
  - --label=org.opencontainers.image.revision={{ .FullCommit }}
  - --label=org.opencontainers.image.licenses=MIT

docker_manifests:
- name_template: micro/{{ .ProjectName }}:{{ .RawVersion }}
  image_templates:
  - micro/{{ .ProjectName }}:{{ .RawVersion }}-amd64
  - micro/{{ .ProjectName }}:{{ .RawVersion }}-arm64v8
- name_template: micro/{{ .ProjectName }}:latest
  image_templates:
  - micro/{{ .ProjectName }}:{{ .RawVersion }}-amd64
  - micro/{{ .ProjectName }}:{{ .RawVersion }}-arm64v8

