FROM alpine:latest
ENV USER=micro
ENV GROUPNAME=$USER
ARG UID=1001
ARG GID=1001
RUN addgroup --gid "$GID" "$GROUPNAME" \
    && adduser \
    --disabled-password \
    --gecos "" \
    --home "/micro" \
    --ingroup "$GROUPNAME" \
    --no-create-home \
    --uid "$UID" "$USER"
RUN apk --no-cache add git make gcc g++ curl ca-certificates
ENV PATH /usr/local/go/bin:/$USER/go/bin:$PATH
COPY --from=golang:1.20.14-alpine /usr/local/go /usr/local/go
COPY micro-amd64 /usr/local/go/bin/micro
USER ${USER}
WORKDIR /micro
EXPOSE 8080
EXPOSE 8081
ENTRYPOINT ["/usr/local/go/bin/micro"]
CMD ["--help"]
