name: Update docs

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      -
        name: Update pkg.go.dev docs
        uses: andrewslotin/go-proxy-pull-action@master
      -
        name: Goreportcard publish
        run: |-
          echo ${{ github.repository }}
          curl -X POST -F "repo=github.com/${{ github.repository }}" https://goreportcard.com/checks
