name: Sanity Cross Build
on: pull_request

permissions:
  contents: read

jobs:
  prtest:
    name: PR sanity check
    runs-on: ubuntu-latest
    steps:
    -
      name: Check out code
      uses: actions/checkout@v4
    -
      name: Check Go mod sanity
      run: |
        echo "Checking if go mod has unneeded comments"
        while read p; do
          ! grep -R "$p" go.mod
        done <./test/gomod_forbidden_words.txt
    -
      name: Run dry cross build
      run: make gorelease-dry-run
    -
      name: Golangci lint
      uses: golangci/golangci-lint-action@v5
      with:
        version: latest
