name: Archives

on:
  push:
    branches-ignore:
      - '**'
    tags:
      - 'v*.*.*'
env:
  GORELEASER_VERSION: v1.20.6

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
      pull-requests: write
      repository-projects: write

    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Fetch tags
        run: git fetch --prune --unshallow --tags -f
      -
        name: Setup release environment
        run: |-
          cat > docker-creds.json <<EOF
          {
            "registries": [
                {
                    "user": "${{ github.actor }}",
                    "pass": "${{ secrets.GITHUB_TOKEN }}",
                    "registry": "ghcr.io"
                },
                {
                    "user": "${{ secrets.DOCKER_USERNAME }}",
                    "pass": "${{ secrets.DOCKER_PASSWORD }}",
                    "registry": "docker.io"
                }
            ]
          }
          EOF
      -
        name: GoReleaser docker
        run: |-
          docker run \
            -t --rm \
            -e CGO_ENABLED=1 \
            -e "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" \
            -e "DOCKER_CREDS_FILE=docker-creds.json" \
            -e "DOCKER_FAIL_ON_LOGIN_ERROR=true" \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v `pwd`:/micro \
            -w /micro \
            ghcr.io/goreleaser/goreleaser-cross:${{ env.GORELEASER_VERSION }} \
            release --clean --verbose

      # -
      #   name: Update pkg.go.dev docs
      #   uses: andrewslotin/go-proxy-pull-action@master
      # -
      #   name: Goreportcard publish
      #   run: |-
      #     curl -X POST -F "repo=github.com/${{ github.repository }}" https://goreportcard.com/checks
