name: Artifacts

on:
  push:
    tags:
      - 'v*.*.*'
env:
  GORELEASER_VERSION: v1.20.6

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write

    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Fetch tags
        run: git fetch --prune --unshallow --tags -f
      -
        name: GoReleaser archives
        run: |-
          docker run \
            --rm \
            -e CGO_ENABLED=1 \
            -e "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" \
            -v `pwd`:/micro \
            -w /micro \
            ghcr.io/goreleaser/goreleaser-cross:${{ env.GORELEASER_VERSION }} \
            release --clean --verbose

