name: Tests
on: push

jobs:
  test:
    name: Test repo
    runs-on: ubuntu-latest
    steps:
    -
      name: Check out code into the Go module directory
      uses: actions/checkout@v4
    -
      name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.20'
        cache: true
    -
      name: Run tests
      env:
        IN_TRAVIS_CI: yes
      run: go test -race -v ./...

